Fix default deny port removal issue
ovn-org/ovn-kubernetes pull request #1800
Opened 2020-11-05 00:37 UTC by astoycos

Fixes #1782

With the code updates to fix problems with orphaned ACLs 
in PR #1665 the code for `localPodDelDefaultDeny` was 
changed in order to be able to clepolicyType:an up NetworkPolicy
resources from both `policy.go` and `namespace.go` 

In order to do so, the `knet.policy` object could no longer
be used in the function call since we didn't have access
to it in `namespace.go` 

Therefore the logic used to determined `PolicyType` was changed
to use only the existing `namespacePolicy` fields egressPolicies and 
ingresPolicies. However it had some issues and the number of egress/ingress
rules weren't enough to tell the `NetworkPolicyType` 

For example, if we had a `NetworkPolicy`
that blocked ALL traffic by default but did not contain any 
ingress/egress rules, the new logic would fail to delete the ports from the 
default deny port group 

FIX: 
Add a `policyType:      policy.Spec.PolicyTypes,`  ensure we can always determine 
the type of `NetworkPolicy` regardless of the number of ingress and egress rules

2020-11-05 14:27 UTC, trozet requested changes
minor syntax changes, otherwise looks good

2020-11-05 14:27 UTC, trozet commented on go-controller/pkg/ovn/policy.go
> +	policyType      []knet.PolicyType
should be "policyTypes"

2020-11-05 14:27 UTC, trozet commented on go-controller/pkg/ovn/policy.go
> +	//Remove port from ingress deny port-group for [Ingress] and [ingress,egress] PolicyTypes
nit: add a space after starting a // comment

2020-11-05 14:27 UTC, trozet commented on go-controller/pkg/ovn/policy.go
> +	//Remove port from ingress deny port-group for [Ingress] and [ingress,egress] PolicyTypes
btw thanks for adding the comments

2020-11-05 16:17 UTC, astoycos commented
@trozet All set!

2020-11-05 18:12 UTC, trozet commented
interesting @astoycos @dcbw looks like there is a race when we delete address set, and then another thread tries to add a peer address to a now nil address set object:

```
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*gressPolicy).destroy()
      /home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/ovn/gress_policy.go:422 +0xac

  github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*gressPolicy).addPeerPod()
      /home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/ovn/gress_policy.go:104 +0xba
```

Looks like we need to check if the gp.peerAddressSet is nil before try to add addresses to it. I think I recently added a check like that in ensurePeerAddressSet. @astoycos can you add another commit here and do a similar check in addPeerPod?

2020-11-05 19:24 UTC, astoycos commented
@trozet sounds good will do

2020-11-05 20:22 UTC, astoycos commented
/retest

2020-11-05 20:52 UTC, trozet commented
/retest

2020-11-05 21:02 UTC, astoycos commented
/retest

2020-11-05 21:47 UTC, astoycos commented
/retest

2020-11-05 23:18 UTC, astoycos commented
/retest

2020-11-06 17:11 UTC, trozet requested changes

2020-11-06 17:11 UTC, trozet commented on go-controller/pkg/ovn/gress_policy.go
> +		return fmt.Errorf("peer AddressSet is nil, cannot add peer pod: %s", pod.ObjectMeta.Name)
maybe add the policy name here as well?

2020-11-06 21:05 UTC, trozet approved these changes

2020-11-06 21:05 UTC, merged