newOvnAddressSets: return interface instead of concrete type
ovn-org/ovn-kubernetes pull request #2216
Opened 2021-05-12 11:17 UTC by fedepaol

**- What this PR does and why is it needed**

If we return a concrete type, the interface assigned to it will not be
nil and it will result in a bad assigned value making us think the field
is set. In particular, having
nsInfo.addressSet, err = oc.createNamespaceAddrSetAllPods(ns)
called twice would result in having the interface not being nil but the
value behind it being nil.

More references in 
https://glucn.medium.com/golang-an-interface-holding-a-nil-value-is-not-nil-bb151f472cc7

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

2021-05-12 14:06 UTC, trozet requested changes
Awesome find @fedepaol . I think perhaps instead of making this hard on ourselves we should just return a struct type instead of an interface:
https://gist.githubusercontent.com/trozet/081643c2cc2fb9ac94d284f5d6b5e237/raw/d3ee4af27f1cefa53f57f0b5adf809c212c45742/gistfile1.txt

We dont have multiple types here for address sets, so there's really no point I can see in using an interface here.

2021-05-12 14:13 UTC, fedepaol commented
> Awesome find @fedepaol . I think perhaps instead of making this hard on ourselves we should just return a struct type instead of an interface:
> https://gist.githubusercontent.com/trozet/081643c2cc2fb9ac94d284f5d6b5e237/raw/d3ee4af27f1cefa53f57f0b5adf809c212c45742/gistfile1.txt
> 
> We dont have multiple types here for address sets, so there's really no point I can see in using an interface here.

Yep, and I think it's more idiomatic too, as in "accepting interfaces and returning concrete types".
Will change that.

2021-05-12 14:51 UTC, fedepaol commented
> > Awesome find @fedepaol . I think perhaps instead of making this hard on ourselves we should just return a struct type instead of an interface:
> > https://gist.githubusercontent.com/trozet/081643c2cc2fb9ac94d284f5d6b5e237/raw/d3ee4af27f1cefa53f57f0b5adf809c212c45742/gistfile1.txt
> > We dont have multiple types here for address sets, so there's really no point I can see in using an interface here.
> 
> Yep, and I think it's more idiomatic too, as in "accepting interfaces and returning concrete types".
> Will change that.

Actually, by doing that we would loose the mock support we currently have so I am a bit torn.

2021-05-12 15:19 UTC, dcbw commented
@fedepaol don't we want:

```
// NewAddressSet returns a new address set object
func (asf *ovnAddressSetFactory) NewAddressSet(name string, ips []net.IP) (AddressSet, error) {
	as, err := newOvnAddressSets(name, ips)
	if err != nil {
		return nil, err
	}
	return as, nil
}
```

2021-05-12 15:22 UTC, fedepaol commented
> @fedepaol don't we want:
> 
> ```
> // NewAddressSet returns a new address set object
> func (asf *ovnAddressSetFactory) NewAddressSet(name string, ips []net.IP) (AddressSet, error) {
> 	as, err := newOvnAddressSets(name, ips)
> 	if err != nil {
> 		return nil, err
> 	}
> 	return as, nil
> }
> ```
> 
> eg, never directly return a concrete-type-returning function in a function that returns an interface? Always return `nil` directly for interface types.

Yup that's another option. I guess the one I posted initially is the worst looking one :-)

2021-05-12 15:28 UTC, dcbw commented
I wish there was a linter option for this :(

2021-05-12 18:38 UTC, dcbw commented on go-controller/pkg/ovn/address_set/address_set.go
> +	if res != nil {
@fedepaol `if err != nil {` I presume?

2021-05-12 18:39 UTC, fedepaol commented on go-controller/pkg/ovn/address_set/address_set.go
> +	if res != nil {
dang

2021-05-12 18:40 UTC, fedepaol commented on go-controller/pkg/ovn/address_set/address_set.go
> +	if res != nil {
Updated, thanks for spotting that

2021-05-13 00:56 UTC, dcbw commented
Build failed becuase our OVN got GCed from Fedora; we're working on that and hope to have a rebuilt OVN package tomorrow.

2021-05-13 16:38 UTC, dcbw commented
@fedepaol rebase please, then it should be ok. Thanks!

2021-05-13 17:10 UTC, fedepaol commented
> @fedepaol rebase please, then it should be ok. Thanks!

rebased

2021-05-13 17:14 UTC, fedepaol commented
/retest

2021-05-13 18:28 UTC, trozet approved these changes
lgtm, no segfaults in downstream scale up last night

2021-05-13 18:37 UTC, merged