Use libovsdb in unidling controller
ovn-org/ovn-kubernetes pull request #2262
Opened 2021-06-15 17:21 UTC by dave-tucker

**- What this PR does and why is it needed**

Based on #2217
This switches the `unidling` controller from `fork/exec` of `ovn-nbctl` on a ticker, to setting up a monitor for the `Controller_Event` table, adding any `empty_lb_backends` events to a channel, and processing those events when received.
It also adds a test with a mock southbound db server to show how this can be tested.

**- Special notes for reviewers**

NOTE: This won't compile right now. There are a couple of fixes that I want in `libovsdb` and then I'll update #2217 and rebase accordinginly.

**- How to verify it**

**- Description for the changelog**

2021-06-21 11:23 UTC, jcaamano commented on go-controller/pkg/util/libovsdb.go
> +func newClient(cfg config.OvnAuthConfig, dbModel *model.DBModel, reconnectFn ReconnectFunc, stopCh <-chan struct{}) (client.Client, error) {
A name like `onReconnectFn` would have helped me understand better what this is for.

2021-06-30 14:29 UTC, dave-tucker commented
Now rebased on #2274 but incomplete as there is no way to add an EventHandler in the util function due to the util function not being aware of my channel. This may end up requiring https://github.com/ovn-org/libovsdb/pull/176

2021-10-29 18:52 UTC, dave-tucker commented
@dcbw @trozet this is ready to go. Just let me know if you want me to pop that last commit or not.

2021-11-02 13:48 UTC, dave-tucker commented
Since #2507 closed, this also carries the fix to only monitor certain SBDB tables, so if CI is green now this is rebased it should 100% be good to go

2021-11-02 17:56 UTC, dave-tucker commented
/retest

2021-11-03 13:17 UTC, dave-tucker commented
/retest

2021-11-04 16:04 UTC, dave-tucker commented
Popped last commit since it was broken out in to #2627

2021-12-03 20:43 UTC, trozet requested changes
looks good @dave-tucker . One minor comment inline. When you push your next version we can make sure it works with the latest libovsdb changes.

2021-12-03 20:43 UTC, trozet commented on go-controller/pkg/ovn/controller/unidling/unidle.go
> +	ctx := context.Background()
can you use a context with a the regular ovsdb timeout like we've updated other parts of the code to use?

2021-12-10 19:14 UTC, dcbw commented
Nice cleanup.
/lgtm

2021-12-10 19:14 UTC, merged