Add a way to provide API token file
ovn-org/ovn-kubernetes pull request #2872
Opened 2022-03-24 14:30 UTC by kyrtapz

API token can expire and we should not rely only on the token itself.
If BearerTokenFile is provided it is periodically read and takes precedence over BearerToken.

More info on SA token expiration: https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/1205-bound-service-account-tokens/README.md#safe-rollout-of-time-bound-token

Signed-off-by: Patryk Diak <pdiak@redhat.com>

2022-03-24 14:36 UTC, kyrtapz commented
/cc @squeed @zshi-redhat

2022-03-25 12:56 UTC, jcaamano requested changes

2022-03-25 12:56 UTC, jcaamano commented on go-controller/pkg/config/config_test.go
> +		defer os.Setenv("K8S_TOKENK8S_TOKEN_FILE", "")
typo

2022-03-25 17:12 UTC, jcaamano commented
/retest

2022-03-28 09:56 UTC, squeed commented
all green!

2022-03-28 11:48 UTC, jcaamano commented
LGTM

2022-03-28 11:48 UTC, merged