gateway/shared: snat hairpin traffic to other node addresses
ovn-org/ovn-kubernetes pull request #2877
Opened 2022-03-28 15:10 UTC by squeed

There is a very special class of traffic, where a load balancer backend
is a different address on the node. This works for pod -> service ->
backend traffic, since it goes out via the management port.

This does not work for host -> pod -> host case though. So, all traffic
that matches this.

This includes a bit of glue to re-sync flows when node IPs change.

Signed-off-by: Casey Callendrello <cdc@redhat.com>

2022-03-28 15:10 UTC, squeed commented
fyi @zshi-redhat

2022-03-29 01:56 UTC, zshi-redhat commented
Would it make sense to trigger the flow insertion based on service endpoint? 
For example, when service endpoint pointing to other node addresses is created.

2022-03-29 08:31 UTC, squeed commented
I wonder if this is going to somehow break EgressIPs. Hmm. Have to think about this. I don't think so, since to match this flow, traffic would have to have the node's source IP and yet be entering breth0 through the patch port.

2022-03-29 08:32 UTC, squeed commented
> Would it make sense to trigger the flow insertion based on service endpoint? For example, when service endpoint pointing to other node addresses is created.

We could, but then we'd have to resync all services any time a node's addresses changed. Is there any reason not to have this flow always?

2022-03-29 08:56 UTC, zshi-redhat commented
> > Would it make sense to trigger the flow insertion based on service endpoint? For example, when service endpoint pointing to other node addresses is created.
> 
> We could, but then we'd have to resync all services any time a node's addresses changed. Is there any reason not to have this flow always?

no particular reason, just that it may not be needed for other use cases.

2022-03-29 11:40 UTC, squeed commented
The test failure is related to dual-stack host-network services, so it could theoretically be relevant, though unlikely. I'll take a look.

2022-03-29 11:40 UTC, squeed commented
/retest

2022-03-29 11:41 UTC, squeed commented
After talking with @zshi-redhat, we decided that it wasn't worth it to tie this in with services, since that makes the data dependencies very complicated (especially on resync). The "extra" flows aren't hurting anything.

2022-03-29 13:48 UTC, tssurya commented
@squeed : could you also update the docs that tim has in the docs/design repo to include this new flow's information?

2022-03-29 14:54 UTC, squeed commented
@tssurya docs updated!

2022-03-29 14:56 UTC, squeed commented
> Overall looks good. I remember we discussed that additionally host->service->secondary node ip on another node wouldn't work. Do you know what is missing to make that work? Can you make a github issue for that gap?

This is only super relevant for secondary IPs that aren't routable, which means we probably don't need to care about that case. If the secondary IPs are routable, then it will Just Work and we don't have to do anything -- it's the same as a HostNetwork-backed service on another node.

If we want to expose non-routable addresses across OVN, then that's another conversation. I don't think we want to do that, it might be a big surprise for users. That's like exposing `loopback` cluster-wide.

> 
> Additionally, can you add an e2e control plane test for your patch?

Sure, will do.

2022-03-30 14:36 UTC, squeed commented
@trozet added an e2e test. PTAL

2022-03-30 18:51 UTC, trozet approved these changes
/lgtm

2022-03-30 18:51 UTC, trozet commented on test/e2e/service.go
> +		// time.Sleep(5 * time.Minute)
nit: remove

2022-03-30 18:52 UTC, trozet requested changes
Looks like the new test is flaking:
[Fail] Services [It] All service features work when manually listening on a non-default address 
/home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/service.go:183

[Fail] Services [It] All service features work when manually listening on a non-default address 
/home/runner/go/pkg/mod/k8s.io/kubernetes@v1.22.2/test/e2e/framework/pods.go:103

https://github.com/ovn-org/ovn-kubernetes/runs/5756567320?check_suite_focus=true

2022-04-12 11:15 UTC, squeed commented
This PR needed a bit of an update -- turns out that local gateway had this problem too, and uses the same flow code as shared.

2022-04-12 12:54 UTC, squeed commented
There. Fixed. That should do it.
@trozet ready for a final review :)

2022-04-12 14:36 UTC, trozet approved these changes
/lgtm

2022-04-12 14:36 UTC, merged