Add e2e test to simulate control plane node reboot
ovn-org/ovn-kubernetes pull request #2936
Opened 2022-04-19 16:48 UTC by jluhrsen

These tests simply kills the control plane pods to simulate the
reboot scenario.

This test does not really simulate the reboot, because:
 1) Kind cluster's etcd stores data in-memory and it looses that data
    after the reboot, so we skip deleting this pod.
 2) Deleting the ovs-node pod will tear down the pod networking and
    and the restart does not build it back, so we skip deleting this
    pod as well.

this is work picked up from an old PR by Anil:
  https://github.com/ovn-org/ovn-kubernetes/pull/1891

Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>

2022-04-19 20:25 UTC, jluhrsen commented
/retest-failed

2022-10-06 04:22 UTC, jluhrsen commented
/retest-failed

2022-10-12 20:42 UTC, trozet requested changes

2022-10-12 20:42 UTC, trozet commented on test/e2e/e2e.go
> +		testPod := <-podChan
i think you need to read from the errChan first before you read from the podChan according to the checkContinuousConnectivity text

2022-10-12 20:42 UTC, trozet commented on test/e2e/e2e.go
> +		testPod := <-podChan
same here

2022-10-12 20:42 UTC, trozet commented on test/e2e/e2e.go
> +	framework.Logf(fmt.Sprintf("master instance of ovnkuber-master is running on node %s", ovnkubeMasterNode))
nit: ovnkube-master

2022-10-21 08:38 UTC, martinkennelly commented on test/e2e/e2e.go
> +	ginkgo.FIt("should provide Internet connection continuously when all pods are killed on node running master instance of ovnkube-master.", func() {
```suggestion
	ginkgo.It("should provide Internet connection continuously when all pods are killed on node running master instance of ovnkube-master.", func() {
```
Didnt review the rest of this but just noticed this.

2022-11-02 18:16 UTC, trozet approved these changes

2022-11-02 18:16 UTC, merged