Allow empty nexthop in L3GatewayConfig annotation
ovn-org/ovn-kubernetes pull request #3231
Opened 2022-10-18 09:19 UTC by zshi-redhat

Default gateway requirement was removed in 3eeb93079, but the L3GatewayConfig UnmarshalJSON function still expects non-empty nexthop value in L3GatewayConfig.

Signed-off-by: Zenghui Shi <zshi@redhat.com>

2022-10-18 11:37 UTC, maiqueb requested changes
The code looks good, but can you throw in a couple of unit tests to assert the behavior ?

2022-10-21 08:50 UTC, zshi-redhat commented
> The code looks good, but can you throw in a couple of unit tests to assert the behavior ?

Done. It turns out that the L3GatewayConfig UnmarshalJSON was disabled, I re-enabled it and add a few more test cases.

2022-10-21 10:55 UTC, zshi-redhat commented
/retest

2022-10-21 20:04 UTC, trozet approved these changes
thanks for testing/catching this @zshi-redhat !

2022-10-21 20:04 UTC, merged