addMasqueradeRoute: use gateway interface IPs
ovn-org/ovn-kubernetes pull request #3336
Opened 2023-01-04 12:48 UTC by jcaamano

Thoughout node gateway initialization, the gateway interface IPs are
used except in addMasqueradeRoute which was recently updated to use the
node status internal IPs as source addresses in the added routes.
However, there might be circumstances where the node status internal IPs
are not current (in our case, a dual-stack conversion procedure in
which kubelet is not configured with the newly acquired IPv6 address and
restarted, which in itself is a problem that would need to be fixed).

Use the interface IPs instead for overall consistency with the rest of
the gateway initialization procedure.

Also fix DPU. Masquerading should not be needed in the DPU (when
newSharedGateway is called with mode NodeModeDPU), only in the
host (where initGatewayDPUHost is use instead for NodeModeDPUHost).
Ref: https://github.com/openshift/ovn-kubernetes/blob/master/docs/design/dpu_support.md

Signed-off-by: Jaime Caamaño Ruiz <jcaamano@redhat.com>

2023-01-04 12:48 UTC, jcaamano commented
@trozet @maiqueb PTAL

2023-01-04 13:34 UTC, maiqueb approved these changes
Makes sense to me.

2023-01-05 17:16 UTC, trozet requested changes
I struggled to remember why I chose the node internal IP, but now I think I remember. In certain cases someone may add an additional IP to the br-ex. Some cases are keepalived adding a VIP, as well as in hypershift an address is added: https://github.com/ovn-org/ovn-kubernetes/pull/2877/files#diff-99202c4c919fcae1a88c767d659a4d92b180a5c30d6f61f2a7faf0e53c6128f0R189

IIRC there are cases where the secondary or deprecated flags wont save us (I think ipv6 and secondary had an issue with keepalived, as well as adding the hypershift IP will be a primary IP). I would need to double check these to be sure. A user could also add an extra IP onto this interface if they want to.

The thing is with the way our logic works is we know that the node internal IP is going to be what the endpoint is bound to, unless someone manually creates an endpoint and binds the app itself to that IP (which is what casey's fix covered). This means that in the default case we know the return packet should always be using the node internal IP address, but we cannot be sure the first address we picked on the interface is the same.

Maybe it makes more sense to fix the dualstack conversion procedure rather than introduce risk here?

2023-01-05 17:37 UTC, jcaamano commented
We could use the node status IPs but fallback to some interface IP in case we did not find an appropriate IP in the node status? At least that would buy us time improving an scenario that is not currently working anyway.

2023-01-10 15:01 UTC, trozet reviewed
one comment, otherwise lgtm

2023-01-10 16:37 UTC, merged