Fix egress firewall to allow inbound conneciton in both gw modes
ovn-org/ovn-kubernetes pull request #3338
Opened 2023-01-05 13:06 UTC by npinaeva

Unify egress firewall implementation for both gateway modes,
move all acls to the node switches.
Unify unit tests for both gateway modes.
Make sure egress firewall allows inbound connections.

Signed-off-by: Nadia Pinaeva <npinaeva@redhat.com>

2023-01-11 17:36 UTC, trozet requested changes

2023-01-11 18:27 UTC, npinaeva commented on go-controller/pkg/ovn/egressfirewall.go
> +	klog.Infof("Adding rule %s", aclName)
lol that was a part of my testing, deleted

2023-01-12 17:17 UTC, npinaeva commented
/retest-failed

2023-01-12 20:09 UTC, trozet approved these changes

2023-01-12 20:09 UTC, merged