Consolidate DPU Host gateway initialization
ovn-org/ovn-kubernetes pull request #3514
Opened 2023-03-30 17:25 UTC by jcaamano

Refactor DPU Host gateway initialization to consolidate it with the other gateway modes.

2023-03-31 11:23 UTC, jcaamano commented
/retest-failed

2023-04-12 11:39 UTC, DmytroLinkin commented
What are the benefits of this refactor? IMO, with all this additional `if`s and especially `switch` code is more spaghetti'sh.

2023-04-12 12:45 UTC, jcaamano commented
> What are the benefits of this refactor? IMO, with all this additional `if`s and especially `switch` code is more spaghetti'sh.

A consolidated view of what we are doing for each gateway mode and less code duplication?

And because of that, there is actually much less if's with the changes than before if you count them. And the switch was already there.

2023-04-12 12:54 UTC, jcaamano commented
Also using the gateway interface so that initialization is asynchronous just as with the other gateway modes.

2023-04-12 13:58 UTC, jcaamano commented
I don't think `initGateway()` is significantly worse than what it was but I am open for specific suggestions. I have no problem rebasing if required after your changes.

It just makes no sense that DPU Host is initialized differently to the other gateway modes while still having so much in common.

2023-04-12 14:59 UTC, DmytroLinkin commented
> I don't think `initGateway()` is significantly worse than what it was but I am open for specific suggestions. I have no problem rebasing if required after your changes.

Yes it doesn't. But with incremental development this "slight worsening" had accumulated over time and we have what do we have now 😄
As for the rebase, I don't see my PR will be merged soon, so yeah, no problem here)

> 
> It just makes no sense that DPU Host is initialized differently to the other gateway modes while still having so much in common.

Could be. I haven't looked into the code so deeply to check differences.

2023-04-12 14:59 UTC, DmytroLinkin commented on go-controller/pkg/node/gateway_init.go
> +	if config.OvnKubeNode.Mode != types.NodeModeFull && config.Gateway.Mode != config.GatewayModeShared {
Isn't it better to check this at config.go?

2023-04-12 15:02 UTC, DmytroLinkin commented on go-controller/pkg/node/gateway_init.go
> +		}
You can move this code inside gatewayInitInternal and drop this `if` block, which will also reduce number of arguments given to the functions

2023-04-12 15:07 UTC, DmytroLinkin commented on go-controller/pkg/node/gateway_shared_intf.go
> +	klog.Info("Creating DPU Host Shared Gateway")
Remove. Duplicates L333

2023-04-12 15:21 UTC, DmytroLinkin requested changes
Here are few suggestions. I'll return to review later, because don't like how, in general, gateway interface and interface addresses are retrieved. Basically they are used to create bridge layout. Within my PR I moved related functions into `bridgeForInterface`. With centralized gateway initialization it will be complicated now. Maybe You could look onto my PR and give some thoughts?

2024-04-30 16:03 UTC, trozet commented
PR has gone stale. If you want you can rebase and reopen if you plan to work on it.

2024-04-30 16:03 UTC, closed without merging