Ignore hybrid-overlay nodes from EgressIP controller
ovn-org/ovn-kubernetes pull request #4093
Opened 2024-01-16 16:30 UTC by kyrtapz

EgressIP is not supported on hybrid-overlay nodes. 
Exclude hybrid-overlay nodes from EgressIP controller to avoid issues related to missing annotations.

/cc @martinkennelly

2024-01-17 10:00 UTC, martinkennelly approved these changes

2024-01-18 10:01 UTC, tssurya commented
/assign @tssurya 
I will look at this this week.

2024-01-19 09:00 UTC, tssurya requested changes
thanks @kyrtapz for the PR, Overall lgtm, left some inline questions.

2024-01-19 09:00 UTC, tssurya commented on go-controller/pkg/clustermanager/egressip_controller_test.go
> +				hybridOverlayNode := v1.Node{
+1 thanks for the UT!

2024-01-19 12:40 UTC, kyrtapz commented on go-controller/pkg/clustermanager/egressip_event_handler.go
> +		if util.NoHostSubnet(node) {
ovnkube-node is not running on hybrid-overlay nodes so this code is not going to be executed anyway.

2024-01-19 12:49 UTC, kyrtapz commented on go-controller/pkg/clustermanager/egressip_event_handler.go
> +		if util.NoHostSubnet(newNode) {
EgressIP is not currently expected to work during live migration. The feature should still work after the migration is completed and the changes in the PR don't affect that.
Handling nodes moving to HO for egressIP requires more effort, especially configuring the appropriate OVN flows etc.

2024-01-19 13:03 UTC, tssurya commented on go-controller/pkg/clustermanager/egressip_event_handler.go
> +		if util.NoHostSubnet(newNode) {
ack agreed as of now that this is not in this PR's scope then.

2024-01-19 13:04 UTC, tssurya commented on go-controller/pkg/clustermanager/egressip_event_handler.go
> +		if util.NoHostSubnet(node) {
aha! dammit I totally missed that point. true.

2024-01-19 13:06 UTC, tssurya approved these changes
LGTM.
little blind here since we don't have e2e's for EIP+Windows but the fix seems non-risky and straight forward. Gonna merge this.

2024-01-19 13:08 UTC, merged