control file is not same as sock file
ovn-org/ovn-kubernetes pull request #4266
Opened 2024-04-09 19:33 UTC by girishmg

control file is used to communicate with the running daemon to modify its properties, whereas sock file is AF_UNIX transport to run OVSDB protocol over

@trozet should be an easy one

2024-04-11 08:00 UTC, tssurya requested changes
lgtm some nits:

in the UT:
there are instances of:
"negative: run `ovn-appctl -t sbdbCtlSockPath` command",
mt.Errorf("failed to execute ovn-appctl -t sbdbCtlSockPath command"),
"positive: run `ovn-appctl -t sbdbCtlSockPath` command",
failed to execute ovn-appctl -t sbdbCtlSockPath command"
can we clean them up too?

2024-04-11 08:00 UTC, tssurya commented on go-controller/pkg/util/ovs.go
>  		"-t",
could you fix the:
`// RunOVNSBAppCtl runs an 'ovn-appctl -t sbdbCtlSockPath command'.`
doc string here?

2024-04-12 10:50 UTC, martinkennelly approved these changes

2024-04-13 08:41 UTC, tssurya approved these changes

2024-04-13 08:42 UTC, merged