kind: Add parameter to configure overlay MTU
ovn-org/ovn-kubernetes pull request #4345
Opened 2024-05-08 11:15 UTC by qinqon

**- Special notes for reviewers**
kind: Add parameter to configure overlay MTU

**- Description for the changelog**
kind: Add parameter to configure overlay MTU

2024-05-08 11:20 UTC, jcaamano submitted a review, later dismissed

2024-05-09 23:42 UTC, girishmg requested changes

2024-05-09 23:42 UTC, girishmg commented on contrib/kind.sh
> +    echo "-mtu                                Define the overlay mtu"
why is this option not using `--`?

2024-05-09 23:42 UTC, girishmg commented on contrib/kind.sh
> +            -mtu  )                             shift
please change here as well?

2024-05-10 15:07 UTC, merged