e2e, udn: Exclude ipv6 gateway address
ovn-org/ovn-kubernetes pull request #4487
Opened 2024-07-01 15:29 UTC by qinqon

#### What this PR does and why is it needed
Exclude the .1 from ipv6 subnet at udn e2e tests, so it do not collide with default gw configuration at pod.

-->
```release-note
NONE
```

2024-07-01 15:40 UTC, npinaeva submitted a review, later dismissed
Fixed the problem for me!

2024-07-01 16:30 UTC, tssurya requested changes

2024-07-01 16:30 UTC, tssurya commented on test/e2e/network_segmentation.go
> +			externalServiceIPv6IP        = "2014:100:200::1"
can you please rename this to gatewayIP?

2024-07-02 06:57 UTC, tssurya approved these changes
will merge when CI is ready

2024-07-02 09:52 UTC, merged