udn, config: a layer2 primary UDN requires subnets
ovn-org/ovn-kubernetes pull request #4556
Opened 2024-07-22 14:41 UTC by maiqueb

#### What this PR does and why is it needed

Throw an error if the subnets attribute is not defined for primary user defined networks of `layer2` topology.

The controllers require the subnet attribute to properly configure the GW for egressing the workload traffic.

#### Which issue(s) this PR fixes

Fixes #

#### Special notes for reviewers

#### How to verify it

#### Details to documentation updates

#### Description for the changelog

#### Does this PR introduce a user-facing change?

```release-note
Primary user defined networks of layer2 topology must have the subnets attribute defined.
```

2024-07-22 14:43 UTC, qinqon approved these changes
/lgtm

2024-07-22 14:57 UTC, tssurya requested changes

2024-07-22 14:57 UTC, tssurya commented on go-controller/pkg/util/multi_network.go
> +		return nil, fmt.Errorf("the subnet attribute must be defined for primary user defined primary networks")
```suggestion
		return nil, fmt.Errorf("the subnet attribute must be defined for layer2 primary user defined networks")
```

2024-07-22 18:07 UTC, maiqueb commented
/test build-pr

2024-07-22 18:08 UTC, maiqueb commented
/test Build-PR

2024-07-23 08:15 UTC, tssurya approved these changes
logic LGTM but I cannot merge this, CI for net-seg is failing. we need to understand why

2024-07-23 08:16 UTC, tssurya commented
@maiqueb : PTAL https://github.com/ovn-org/ovn-kubernetes/actions/runs/10048260310/job/27772971636?pr=4556

2024-07-24 14:31 UTC, tssurya commented
saved flake for future, merging this now given this PR is mostly harmless

2024-07-24 14:31 UTC, merged