UDN: L3: Use nodesubnet annotations for L3; not clustersubnet from NAD
ovn-org/ovn-kubernetes pull request #4718
Opened 2024-09-11 10:13 UTC by tssurya

For UDN L3, it seems the local LRSR and LRPs are not getting created correctly.

I see errors like:
```
surya@fedora:~/go/src/github.com/ovn-org/ovn-kubernetes/go-controller$ oc logs -n ovn-kubernetes ovnkube-node-xrb6k ovn-northd | grep "No path for static"
2024-09-11T09:15:39.002Z|00013|northd|WARN|No path for static route 10.128.0.0/24; next hop 100.88.0.2
```
and
```
2024-09-11T09:15:39.003Z|00013|northd|WARN|No path for static route 2014:100:200:1::/64; next hop fd97::3
```
etc happening.

See a snippet of default network routes:
```
sh-5.2# ovn-nbctl lr-route-list ovn_cluster_router                                                                                                                          
IPv4 Routes
Route Table <main>:
               100.64.0.2                100.88.0.2 dst-ip
               100.64.0.3                100.64.0.3 dst-ip
               100.64.0.4                100.88.0.4 dst-ip
            10.244.0.0/24                100.88.0.2 dst-ip
            10.244.2.0/24                100.88.0.4 dst-ip
            10.244.1.0/24                100.64.0.3 src-ip
            10.244.0.0/16                100.64.0.3 src-ip
```
versus:
UDN routes:
```
sh-5.2# ovn-nbctl lr-route-list ovn_cluster_router                                                                                                                          
IPv4 Routes
Route Table <main>:
               100.64.0.2                100.88.0.2 dst-ip
               100.64.0.3                100.64.0.3 dst-ip
               100.64.0.4                100.88.0.4 dst-ip
            10.244.0.0/24                100.88.0.2 dst-ip
            10.244.2.0/24                100.88.0.4 dst-ip
            10.244.1.0/24                100.64.0.3 src-ip
            10.244.0.0/16                100.64.0.3 src-ip
```
we are missing one... the local pod subnet

Also seems like:
```
      1004 inport == "rtos-xfrkk_tenant.red_ovn-worker" && ip4.dst == 172.18.0.3 /* xfrkk_tenant.red_ovn-worker */         reroute                10.128.0.2                 
````
is pulling info from cluster-subnet and not node-subnet for L3

2024-09-11 10:22 UTC, tssurya commented
cc @maiqueb / @trozet / @dceara

2024-09-11 15:42 UTC, tssurya commented
unrelated flake: https://github.com/ovn-org/ovn-kubernetes/actions/runs/10809609667/job/29985084566?pr=4718
```
2024-09-11T10:33:33.3230602Z [91m[1m[Fail] [0m[90mOVN master EgressIP Operations [0m[0mWatchEgressNodes running with WatchEgressIP [0m[91m[1m[It] should re-balance EgressIPs when their node is removed [0m
2024-09-11T10:33:33.3232456Z [37m/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/ovn/egressip_test.go:11879[0m
```

2024-09-11 16:42 UTC, dceara commented
@tssurya don't we need the exact same thing for the secondary L2 network controller?

Also, I'm not sure why the return value of
```
// Subnets returns the Subnets value
func (nInfo *secondaryNetInfo) Subnets() []config.CIDRNetworkEntry {
	return nInfo.subnets
}
```
isn't exactly the right thing we need?

Do we need to fix this instead?
```
func newLayer3NetConfInfo(netconf *ovncnitypes.NetConf) (NetInfo, error) {
	subnets, _, err := parseSubnets(netconf.Subnets, "", types.Layer3Topology)
	if err != nil {
		return nil, err
	}
	joinSubnets, err := parseJoinSubnet(netconf.JoinSubnet)
	if err != nil {
		return nil, err
	}
	ni := &secondaryNetInfo{
		netName:        netconf.Name,
		primaryNetwork: netconf.Role == types.NetworkRolePrimary,
		topology:       types.Layer3Topology,
		subnets:        subnets,
		joinSubnets:    joinSubnets,
		mtu:            netconf.MTU,
		nadNames:       sets.Set[string]{},
	}
	ni.ipv4mode, ni.ipv6mode = getIPMode(subnets)
	return ni, nil
}
```

Do we need a unit test?

Thanks,
Dumitru

2024-09-12 07:14 UTC, maiqueb reviewed
Couldn't we update the node annotation used in the unit tests in such a way we would see this change in the unit tests ? i.e. this extra route would be installed ? 

Having the unit test reproduce the "real" scenario as close as possible would be beneficial IMHO.

2024-09-12 07:14 UTC, maiqueb commented on go-controller/pkg/ovn/secondary_layer3_network_controller.go
> +		return nil, fmt.Errorf("failed to get node %s subnet annotation for network %s : %v", node.Name, oc.GetNetworkName(), err)
please use %q and %w.

2024-09-12 07:16 UTC, tssurya commented
pretty sure the fact that unit tests for this didn't fail is because this annotation is already present. I can double check to see  what's the clustersubnet used v/s node subnet

2024-09-12 07:17 UTC, tssurya commented
@dceara for L2 the subnet is nad's subnet cause its a flat L2 we don't have a per nodesubnet we use there like we do for L3, hence the distinction. L3 should look more like our default one where we use the same method that I am changing in this PR, hope that makes sense

2024-09-12 08:35 UTC, dceara commented
> @dceara for L2 the subnet is nad's subnet cause its a flat L2 we don't have a per nodesubnet we use there like we do for L3, hence the distinction. L3 should look more like our default one where we use the same method that I am changing in this PR, hope that makes sense

Ah I see, ok disregard that part.

2024-09-12 08:50 UTC, tssurya commented
> > pretty sure the fact that unit tests for this didn't fail is because this annotation is already present. I can double check to see what's the clustersubnet used v/s node subnet
> 
> So in the unit tests we are already installing the local pod subnet route, which this PR says it's missing in production ?

right so the problem is not in NBDB level its at SBDB level. northd complains that the prefix we are providing is wrong

see my PR description: `No path for static route 10.128.0.0/24; next hop 100.88.0.2` so this should have been `10.128.0.1/24` which is the subnet for this node, so the best we can do with UTs is to change the distinction on the prefix used. my guess is we are using the same thing as cluster subnet and node subnet and so nothing changed for tests.. I will try to sort the test part out.

2024-09-12 12:20 UTC, tssurya commented
OK! Finally CI looks good. let me see if I can fix the tests here.

2024-09-12 21:02 UTC, trozet requested changes
I provided some context here to what is wrong with the unit tests:
https://github.com/ovn-org/ovn-kubernetes/issues/4723#issuecomment-2347231269

I cant really condone merging this PR without fixing those unit tests first.

2024-09-13 07:07 UTC, tssurya commented
> I provided some context here to what is wrong with the unit tests: [#4723 (comment)](https://github.com/ovn-org/ovn-kubernetes/issues/4723#issuecomment-2347231269)
> 
> I cant really condone merging this PR without fixing those unit tests first.

Just to be clear: https://github.com/ovn-org/ovn-kubernetes/pull/4718#issuecomment-2346135940 I was not asking to merge without tests :) I was going to look into the tests *as part of this PR itself* See my above two comments.

I was looking for a double check/review on the routes/policies changes I am making to see if it made sense since its touching some crucial pieces.

2024-09-13 10:33 UTC, tssurya commented
@maiqueb / @dceara / @trozet : I have fixed the tests to be more explicit, PTAL

2024-09-13 11:01 UTC, tssurya commented
another unrelated EIP flake: https://github.com/ovn-org/ovn-kubernetes/issues/4724

2024-09-13 13:16 UTC, tssurya commented
failures in multi-homing are unrelated: we had a regression merge into multus last night
@jcaamano is fixing it in https://github.com/ovn-org/ovn-kubernetes/pull/4722/commits/9746662fe86df61754dc3b0d53c7a78d14f7941f

2024-09-13 15:19 UTC, trozet approved these changes
thanks @tssurya !

2024-09-13 15:20 UTC, merged